# Generated by Django 3.1.7 on 2021-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='avg_rating',
            new_name='Ratings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_data',
        ),
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.TextField(default='****', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(default='****', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='****', max_length=100),
        ),
    ]
