# Generated by Django 3.1.7 on 2021-04-06 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210406_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
