# Generated by Django 3.1.7 on 2021-04-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Actors',
            new_name='Main_character',
        ),
    ]
