# Generated by Django 3.1.7 on 2021-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210409_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Liked',
        ),
        migrations.AddField(
            model_name='movie',
            name='Upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
