# Generated by Django 3.1.7 on 2021-04-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210409_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Downvote',
            field=models.IntegerField(default=0),
        ),
    ]
