# Generated by Django 3.1.7 on 2021-04-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_movie_downvote'),
    ]

    operations = [
    ]
